version: '3.8'
services:
  bookstore-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=Emorinken
      - POSTGRES_DB=bookstore
    ports:
      - '5432:5432'
    volumes:
      - ~/volumes/jhipster/bookstore/postgresql/:/var/lib/postgresql/data/
